### ISSUE TITLE
When downloading (slowly (1Mbyte/sec)) a big file (1.2Gig) -> OOM

### ISSUE THREAD

**Issue by delandtj** [gigforks/minio#30] opened 2018-03-17 19:14 UTC
https://paste.rs/gAc boom

**Comment by delandtj** [comment] 2018-03-17 20:30
![image](https://user-images.githubusercontent.com/5995555/37559674-6fd3e1ce-2a2a-11e8-9cf6-07c89b7752f5.png)

**Comment by delandtj** [comment] 2018-03-17 20:38
![image](https://user-images.githubusercontent.com/5995555/37559679-8849e6f4-2a2a-11e8-97ab-622347eb8802.png)
between 560 and 700 download , minio gets evicted by OOM

**Comment by delandtj** [comment] 2018-03-17 20:39
[miniolog.txt](https://github.com/gigforks/minio/files/1822059/miniolog.txt)

**Comment by delandtj** [comment] 2018-03-17 20:43
from previous comment, not OOM , but just the crash with that log.

vm : https://be-gen-1.demo.greenitglobe.com/CBGrid/Virtual%20Machine?id=1562

no OOM the last time.
kernel has been upgraded to 4.13 with `nopti noretpoline` parameters added

**Comment by iwanbk** [comment] 2018-03-19 04:34
@delandtj do you use zerostor gateway?

Because AFAIK, we can't even upload such big file with the zerostor gateway

**Comment by iwanbk** [comment] 2018-03-19 04:35
also, how do you simulate the slow download?

**Comment by delandtj** [comment] 2018-03-19 06:11
not ;-) it _is__ slow

**Comment by delandtj** [comment] 2018-03-19 06:13
as for the size of upload : have a look @ the first screenshot, apparently I could

**Comment by zaibon** [comment] 2018-03-19 06:25
@iwanbk it is our 0-stor minio yes.
and the upload from the ui doesn't seems to use multipart upload so there is no limit at the size

**Comment by iwanbk** [comment] 2018-03-19 09:11
tried to reproduce it:
- minio & 0-db on same machine, 1GB of ram & 1GB of swap
- 1.3GB of file
- local network

upload and download from web UI worked fine.

Need to test it with `slow` connection.

**Comment by iwanbk** [comment] 2018-03-21 10:52
Did it use 3a31ddbad156a0a978de8957c226a68ca953214a version?

**Comment by iwanbk** [comment] 2018-03-21 11:14
> miniolog.txt

from this log, i can see there are two active things:
- filemeta of the minio gateway, reading metadata of an object. Metadata of an object is stored in single file, i can't image how big the metadata is to creates the such OOM
- 0-stor's async splitter : i can see how it might become deadlocked, but couldn't see such deadlock will create OOM

i'll continue to use profiler

**Comment by iwanbk** [comment] 2018-03-23 02:27
Finally got the profile data.

I use these steps to get the data:
- start fast downloader (from same machine as minio)
- start slow downloader, using `--limit-rate=600K` of `wget`

I need to repeat several times to get increased memory usage though, so it seems those steps was not the correct way to reproduce it.
 
From the profile data below, although `redigo` hold the memory, it seems to be caused by some stuck goroutines of 0-stor async splitter.
[high.pdf](https://github.com/gigforks/minio/files/1839927/high.pdf)

**Comment by iwanbk** [comment] 2018-03-23 03:16
Another profile from another machine

![heap2](https://user-images.githubusercontent.com/977552/37809717-288c7e18-2e83-11e8-8bc8-d12de8e4e314.png)

**Comment by iwanbk** [comment] 2018-03-23 08:31
A fix attempt has been submitted to https://github.com/zero-os/0-stor/pull/525.

Testing on same machine as https://github.com/gigforks/minio/issues/30#issuecomment-375531104, the memory usage never reach 150MB,  compared to previously 450MB.

**Comment by iwanbk** [comment] 2018-04-05 04:50
Run two continuous 1mbps download for almost 2 hours now, minio server (with 1GB of RAM) has agent for resource usage graphing. Memory usage was stable, minio only use < 10% of RAM.

Will continue the test until tomorrow before closing this issue.

**Comment by iwanbk** [comment] 2018-04-05 05:46
> Run two continuous 1mbps download

One of the download has been changed to this
```
while 1
     limited (1mbps) download
     unlimited download -> result in 72mbps speed
```

still fine

**Comment by iwanbk** [comment] 2018-04-06 02:42
almost 24 hours and memory usage still stable, closing it.

**Closed by iwanbk** 2018-04-06 02:42 UTC
Labels: state_verification, type_bug
