### ISSUE TITLE
super slow and corrupted download

### ISSUE THREAD

**Issue by zaibon** [gigforks/minio#26] opened 2018-03-14 14:29 UTC
Build using : ed0a0d2f4f4e93e9a74f54a134e91de236a4926d

Uploading files works ok, but when trying to download the files back, it takes a long time before the download actually starts and then the file is corrupted. Most of the time I only get a few first KiB of the file.

0-stor config used
```
namespace: miniotest
password: None
datastor: # required
  shards: # required
    - 172.20.0.91:9900
    - 172.20.0.91:9901
    - 172.20.0.91:9902
    - 172.20.0.91:9903
    - 172.20.0.91:9904
    - 172.20.0.91:9905
    - 172.20.0.91:9906
    - 172.20.0.92:9900
    - 172.20.0.92:9901
    - 172.20.0.92:9902
    - 172.20.0.92:9903
    - 172.20.0.92:9904
    - 172.20.0.92:9905
    - 172.20.0.92:9906
  pipeline:
    block_size: 1049000
    compression: # optional, snappy by default
      type: snappy # snappy is the default, other options: lz4, gzip
      mode: default # default is the default, other options: best_speed, best_compression
    encryption: # optional, disabled by default
      type: aes # aes is the default and only standard option
      private_key: ab345678901234567890123456789012
```

**Comment by zaibon** [comment] 2018-03-14 14:55
```
Trace: 1: /home/zaibon/dev/go/src/github.com/minio/minio/cmd/object-handlers.go:172:cmd.objectAPIHandlers.GetObjectHandler()
       2: /home/zaibon/dev/go/src/github.com/minio/minio/cmd/api-router.go:59:cmd.(objectAPIHandlers).GetObjectHandler-fm()
       3: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()
       4: /home/zaibon/dev/go/src/github.com/minio/minio/vendor/github.com/gorilla/mux/mux.go:107:mux.(*Router).ServeHTTP()
       5: /home/zaibon/dev/go/src/github.com/minio/minio/cmd/generic-handlers.go:563:cmd.pathValidityHandler.ServeHTTP()
       6: /home/zaibon/dev/go/src/github.com/minio/minio/cmd/generic-handlers.go:65:cmd.requestSizeLimitHandler.ServeHTTP()
       7: :0:()
       8: /home/zaibon/dev/go/src/github.com/minio/minio/cmd/crossdomain-xml-handler.go:51:cmd.crossDomainPolicy.ServeHTTP()
       9: :0:()
      10: /home/zaibon/dev/go/src/github.com/minio/minio/cmd/generic-handlers.go:219:cmd.redirectHandler.ServeHTTP()
      11: :0:()
      12: /home/zaibon/dev/go/src/github.com/minio/minio/cmd/generic-handlers.go:277:cmd.minioReservedBucketHandler.ServeHTTP()
      13: :0:()
      14: /home/zaibon/dev/go/src/github.com/minio/minio/cmd/generic-handlers.go:246:cmd.cacheControlHandler.ServeHTTP()
      15: :0:()
      16: /home/zaibon/dev/go/src/github.com/minio/minio/cmd/generic-handlers.go:347:cmd.timeValidityHandler.ServeHTTP()
      17: :0:()
      18: /home/zaibon/dev/go/src/github.com/minio/minio/vendor/github.com/rs/cors/cors.go:190:cors.(*Cors).Handler.func1()
      19: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()
      20: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()
      21: /home/zaibon/dev/go/src/github.com/minio/minio/cmd/generic-handlers.go:453:cmd.resourceHandler.ServeHTTP()
      22: /home/zaibon/dev/go/src/github.com/minio/minio/cmd/auth-handler.go:245:cmd.authHandler.ServeHTTP()
      23: :0:()
      24: /home/zaibon/dev/go/src/github.com/minio/minio/pkg/http/server.go:111:http.(*Server).Start.func1()
      25: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()
      26: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()
      27: net/http/server.go:2694:http.serverHandler.ServeHTTP()
      28: net/http/server.go:1830:http.(*conn).serve()
[2018-03-14T14:53:39.576127801Z] [ERROR] Unable to write to client. (read tcp 172.18.0.10:39428->172.20.0.91:9905: i/o timeout)
```

Seems after a while the download fails due to a timeout. I got that trying to download a file of 2MiB +- so that should be fast

**Comment by iwanbk** [comment] 2018-03-15 02:26
Tried it with my config with only two shards, it works fine.

Start with empty files and then create the bucket
```
$ mc ls myzerostor                                                                                                 
ibk@siputih:~/pathgo/src/github.com/minio/minio/cmd/gateway/zerostor
$ mc mb myzerostor/bening
Bucket created successfully `myzerostor/bening`.
```

Then upload 24M of file, `minio` binary
```
ibk@siputih:~/pathgo/src/github.com/minio/minio/cmd/gateway/zerostor
$ ls /tmp/minio -lh                                                                                                
-rwxrwxr-x 1 ibk ibk 24M Mar 15 09:11 /tmp/minio
ibk@siputih:~/pathgo/src/github.com/minio/minio/cmd/gateway/zerostor
$ mc cp /tmp/minio myzerostor/bening/                                                                              
/tmp/minio:          23.46 MB / 23.46 MB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00% 14.98 MB/s 1sibk@siputih:~/pathgo/src/github.com/minio/minio/cmd/gateway/zerostor
```
Download that file and `cmp` it to check
```
$ mc cat myzerostor/bening/minio > /tmp/down                                                                       
ibk@siputih:~/pathgo/src/github.com/minio/minio/cmd/gateway/zerostor
$ cmp /tmp/minio /tmp/down 
ibk@siputih:~/pathgo/src/github.com/minio/minio/cmd/gateway/zerostor
$ mc ls myzerostor/bening
[2018-03-15 09:22:02 WIB]  24MiB minio
```

i'll try to mimic your config

**Comment by iwanbk** [comment] 2018-03-15 03:01
> i'll try to mimic your config

tested with same config, except only use 7 shards, it still works fine.

Have you checked 0-db side, make sure you didn't get https://github.com/rivine/0-db/issues/20.

**Comment by iwanbk** [comment] 2018-03-16 04:00
More tests by me & @zaibon : 
- local test was fine
- minio & 0-db in internet, `mc` in local was fine

seems like 0-os related issue.

I've added some debugging message to #27.
Need to set `MINIO_ZEROSTOR_DEBUG` env variable to `1`

If it previously work with 0-os, the only part changed was 0-stor `ReadRange` addition.
We can disable `ReadRange` by modifying these lines
https://github.com/gigforks/minio/blob/2465039f0f2718869b4a355956f1b5ed898573d8/cmd/gateway/zerostor/zerostor.go#L75-L82

**Comment by zaibon** [comment] 2018-03-17 07:50
https://github.com/zero-os/0-stor/commit/6f3e9fa2d2b714613eaacca7841ca4ee9a588c2a

**Comment by zaibon** [comment] 2018-03-17 07:56
I did a lot of test yesterday here is what I found:
I stripped down the configuration to the most simple thing:
```yaml
namespace: miniotest
password: ''
datastor: # required
  shards: # required
    - 192.168.58.96:9900
    - 192.168.58.96:9901
  pipeline:
    block_size: 1048576
    compression: # optional, snappy by default
      mode: '' # disable compression
    encryption: # optional, disabled by default
      private_key: '' # disable encryption
    distribution:
      data_shards: 2
```
So minio is deployed on the same node as the zdbs, not compression not encryption, just simple replication.
Then I wrote a small test script, that just create a bucket, write a file, download it back and compare:
```shell
#!/bin/bash
set -x

mc mb test/zaibon
mc cp blob test/zaibon
mc ls test/zaibon
rm blob2
mc cat test/zaibon/blob > blob2
diff blob blob2
```

It tested this script with different block size, the script works with up to 64K block size. Above that, the download doesn't work and I get an empty file.

We double check the networking of the containers deployed in 0-os, everything can reach everything.
That was already confirmed just by the fact that the write never fails

**Comment by iwanbk** [comment] 2018-03-19 03:24
> the script works with up to 64K block size. 

In this case, we need info about file size.

> That was already confirmed just by the fact that the write never fails

Why did you sure that this is the case? Not because the failed read?

**Comment by iwanbk** [comment] 2018-03-19 03:59
this is what i got when i tried to kill one of the server
```
+ mc cp blob myzerostor/keruh
mc: <ERROR> Failed to copy `blob`. We encountered an internal error, please try again.
mc: <ERROR> Session safely terminated. To resume session `mc session resume AraQeCuh`
+ mc ls myzerostor/keruh
+ rm blob2
+ mc cat myzerostor/keruh/blob
mc: <ERROR> Unable to read from `myzerostor/keruh/blob`. The specified key does not exist.
+ cmp blob blob2
cmp: EOF on blob2
```

**Comment by zaibon** [comment] 2018-03-19 06:28
Why do you kill a server? I don't get the goal.

I was doing my tests using a 5MiB file.

**Comment by zaibon** [comment] 2018-03-19 06:30
> Why did you sure that this is the case? Not because the failed read?

From the logs of mino and 0-db I don't get any error and I see the writes reaching 0-db

**Comment by iwanbk** [comment] 2018-03-19 07:17
> Why do you kill a server? I don't get the goal.

to simulate failed write

> From the logs of mino and 0-db I don't get any error and I see the writes reaching 0-db

Oh, it seems i misunderstood this

> That was already confirmed just by the fact that the write never fails

I thought you said that the gateway doesn't detect the write error.
And so, the write never fails even it actually failed.

**Comment by iwanbk** [comment] 2018-03-19 08:58
> That was a different issue (#28)

yeah, my bad

**Comment by iwanbk** [comment] 2018-03-19 09:54
>  Above that, the download doesn't work and I get an empty file.

forgot to ask this, what is the error message?

Is it possible that the error was caused by https://github.com/gigforks/minio/issues/16#issuecomment-374141329?

**Comment by iwanbk** [comment] 2018-03-19 10:13
@zaibon 
i think https://github.com/zero-os/0-stor/issues/499#issuecomment-374161968 explain your issue.

**Comment by iwanbk** [comment] 2018-03-19 10:42
@zaibon 

can you apply the patch https://github.com/zero-os/0-stor/issues/499#issuecomment-374168689 (to vendored client)

to 3a31ddbad156a0a978de8957c226a68ca953214a of minio (need to use this commit, because i disabled read range in the next commit)

and see what happen?

**Comment by iwanbk** [comment] 2018-03-21 02:33
> can you apply the patch zero-os/0-stor#499 (comment) (to vendored client)

The fix attempt landed on f9204eea61877dc144bb4e6826831445b9a4099c

**Comment by zaibon** [comment] 2018-03-21 07:10
tested with the new build, still not working, but now I have more logs coming:
```
PutObject bucket:zaibon, object:2Fingz - La Folie Des Glandeurs (2013).zip, metadata:map[content-type:application/zip]
ListObjects bucket:zaibon, prefix:, marker:, delimiter:/, maxKeys:1000
[Wed21 07:08] - zeroos_bootstrap.py:38  :service-8885c708-1111-4645-88e4-001d97c0d50e - INFO     - start discovering new members
GetObject bucket:zaibon, object:2Fingz - La Folie Des Glandeurs (2013).zip, offset:0, length:-1, etag:
	GetObject using zerostor Read
time="2018-03-21T07:08:55Z" level=error msg="failed to read \"\\x00\\x00\\x1a\\x00\\x00\\x00\" from replicated shard \"192.168.58.96:9900\": read tcp 172.18.0.10:35448->192.168.58.96:9900: i/o timeout" 
time="2018-03-21T07:08:55Z" level=error msg="failed to read \"\\x00\\x00H\\x020\\x00\" from replicated shard \"192.168.58.96:9901\": read tcp 172.18.0.10:51372->192.168.58.96:9901: i/o timeout" 
time="2018-03-21T07:08:55Z" level=error msg="failed to read \"\\x00\\x00\\x8e\\x01 \\x00\" from replicated shard \"192.168.58.96:9901\": read tcp 172.18.0.10:51388->192.168.58.96:9901: i/o timeout" 
time="2018-03-21T07:08:55Z" level=error msg="failed to read \"\\x00\\x00\\xbc\\x03P\\x00\" from replicated shard \"192.168.58.96:9901\": read tcp 172.18.0.10:51386->192.168.58.96:9901: i/o timeout" 
GetObject bucket:zaibon, object:2Fingz - La Folie Des Glandeurs (2013).zip, offset:0, length:-1, etag:
	GetObject using zerostor Read
[Wed21 07:08] - zeroos_bootstrap.py:38  :service-8885c708-1111-4645-88e4-001d97c0d50e - INFO     - start discovering new members
time="2018-03-21T07:09:00Z" level=error msg="failed to read \"\\x00\\x00H\\x020\\x00\" from replicated shard \"192.168.58.96:9900\": read tcp 172.18.0.10:35440->192.168.58.96:9900: i/o timeout" 
time="2018-03-21T07:09:00Z" level=error msg="failed replicate-read chunk from any of the configured shards" 
time="2018-03-21T07:09:00Z" level=error msg="failed to read \"\\x00\\x00\\x1a\\x00\\x00\\x00\" from replicated shard \"192.168.58.96:9901\": read tcp 172.18.0.10:51394->192.168.58.96:9901: i/o timeout" 
time="2018-03-21T07:09:00Z" level=error msg="failed replicate-read chunk from any of the configured shards" 
time="2018-03-21T07:09:00Z" level=error msg="failed to read \"\\x00\\x00\\xbc\\x03P\\x00\" from replicated shard \"192.168.58.96:9900\": read tcp 172.18.0.10:35466->192.168.58.96:9900: i/o timeout" 
time="2018-03-21T07:09:00Z" level=error msg="failed replicate-read chunk from any of the configured shards" 
time="2018-03-21T07:09:00Z" level=error msg="failed to read \"\\x00\\x00\\x8e\\x01 \\x00\" from replicated shard \"192.168.58.96:9900\": read tcp 172.18.0.10:35454->192.168.58.96:9900: i/o timeout" 
time="2018-03-21T07:09:00Z" level=error msg="failed replicate-read chunk from any of the configured shards" 
time="2018-03-21T07:09:01Z" level=error msg="failed to read \"\\x00\\x00\\xbc\\x03P\\x00\" from replicated shard \"192.168.58.96:9901\": read tcp 172.18.0.10:51402->192.168.58.96:9901: i/o timeout" 
time="2018-03-21T07:09:01Z" level=error msg="failed to read \"\\x00\\x00\\x1a\\x00\\x00\\x00\" from replicated shard \"192.168.58.96:9900\": read tcp 172.18.0.10:35468->192.168.58.96:9900: i/o timeout" 
time="2018-03-21T07:09:01Z" level=error msg="failed to read \"\\x00\\x00H\\x020\\x00\" from replicated shard \"192.168.58.96:9901\": read tcp 172.18.0.10:51404->192.168.58.96:9901: i/o timeout" 
time="2018-03-21T07:09:01Z" level=error msg="failed to read \"\\x00\\x00\\x8e\\x01 \\x00\" from replicated shard \"192.168.58.96:9901\": read tcp 172.18.0.10:51400->192.168.58.96:9901: i/o timeout" 
time="2018-03-21T07:09:06Z" level=error msg="failed to read \"\\x00\\x00\\xbc\\x03P\\x00\" from replicated shard \"192.168.58.96:9900\": read tcp 172.18.0.10:35478->192.168.58.96:9900: i/o timeout" 
time="2018-03-21T07:09:06Z" level=error msg="failed replicate-read chunk from any of the configured shards" 
time="2018-03-21T07:09:06Z" level=error msg="failed to read \"\\x00\\x00H\\x020\\x00\" from replicated shard \"192.168.58.96:9900\": read tcp 172.18.0.10:35482->192.168.58.96:9900: i/o timeout" 
time="2018-03-21T07:09:06Z" level=error msg="failed replicate-read chunk from any of the configured shards" 
time="2018-03-21T07:09:06Z" level=error msg="failed to read \"\\x00\\x00\\x1a\\x00\\x00\\x00\" from replicated shard \"192.168.58.96:9901\": read tcp 172.18.0.10:51410->192.168.58.96:9901: i/o timeout" 
time="2018-03-21T07:09:06Z" level=error msg="failed replicate-read chunk from any of the configured shards" 
time="2018-03-21T07:09:06Z" level=error msg="failed to read \"\\x00\\x00\\x8e\\x01 \\x00\" from replicated shard \"192.168.58.96:9900\": read tcp 172.18.0.10:35484->192.168.58.96:9900: i/o timeout" 
time="2018-03-21T07:09:06Z" level=error msg="failed replicate-read chunk from any of the configured shards" 
```

**Comment by iwanbk** [comment] 2018-03-21 07:13
> read tcp 172.18.0.10:51410->192.168.58.96:9901: i/o timeout" 
> read tcp 172.18.0.10:35484->192.168.58.96:9900: i/o timeout" 

It seems the 0-db are down

**Comment by zaibon** [comment] 2018-03-21 07:14
nop they are not, I can reach them both

**Comment by iwanbk** [comment] 2018-03-21 07:16
Is this a super slow network? The error message is `i/o timeout`, it failed to read the data within specified timeout

**Comment by zaibon** [comment] 2018-03-21 07:18
no it's all local network, so should be super fast.
The upload of 200MB take +- 1sec

**Comment by iwanbk** [comment] 2018-03-22 08:01
i got similar error on slower machine on local network
```
failed:read tcp 10.130.70.56:32872->10.130.67.161:12345: i/o timeout  
```

The exact same operation worked fine on the faster one on localhost

**Comment by iwanbk** [comment] 2018-03-22 08:36
> define slower machine ? CPU wise less powerful or ?
> What's the difference between the 2 ?

Got more data:

succeed case:
- both minio & zdb on my local machine 
- minio & zdb on same digital ocean VM

failed case:
- minio & zdb on different digialocean VM, connected by DO private network

the VM is smallest DO VM : 1GB of RAM, 1 CPU

test case:
multipart upload of 1.6GB ubuntu iso, with blocksize: 1048576

It did the `read` when doing  multipart `complete`

**Comment by iwanbk** [comment] 2018-03-22 09:47
I can easily reproduce the issue with this
```go
package main

import (
	"crypto/rand"
	"log"

	"github.com/zero-os/0-stor/client/datastor/zerodb"
)

const (
	zdbAddr   = "192.168.0.101:12345"
	passwd    = ""
	namespace = "thedisk"
)

const (
	// settings on which i got the issue
	blockSize = 1048576
	numBlocks = 1548
)

var (
	data []byte
)

func init() {
	data = make([]byte, blockSize)
	n, err := rand.Read(data)
	if n != blockSize || err != nil {
		log.Fatalf("failed to init data. n=%v, err: %v", n, err)
	}
}

func main() {
	cli, err := zerodb.NewClient(zdbAddr, passwd, namespace)
	if err != nil {
		log.Fatalf("create zdb client: %v", err)
	}

	var keys [][]byte

	log.Println("Write")
	// write on some key
	for i := 0; i < numBlocks; i++ {
		key, err := cli.CreateObject(data)
		if err != nil {
			log.Fatalf("[write]failed to create object `%v` : %v", i, err)
		}
		keys = append(keys, key)
	}

	log.Println("re-write")
	// re-write
	for i, key := range keys {
		// read
		_, err := cli.GetObject(key)
		if err != nil {
			log.Fatalf("[re-write] failed to get `%v`: %v", i, err)
		}

		// check validity of the object

		// write again with diff key
	}
}
```

error message
```
failed to get `0`: read tcp 192.168.0.102:37256->192.168.0.101:12345: i/o timeout
```

`0` above means it is the first read

increasing the timeout defined below didn't help

https://github.com/zero-os/0-stor/blob/ab29bd78c7827556b3d94c8a518f02dd1e89fc53/client/datastor/zerodb/client.go#L32-L34

environment:
- client on local machine, zdb on VM

it worked fine when both client and `zdb` on same machine

**Comment by iwanbk** [comment] 2018-03-22 09:48
will simplify the test script and send issue to 0-db repo if the issue still persist

**Comment by iwanbk** [comment] 2018-03-22 10:33
reported to 0-db repo https://github.com/rivine/0-db/issues/28

**Comment by iwanbk** [comment] 2018-03-22 13:49
@zaibon maxux pushed temporary fix, works for me. Please check

**Comment by zaibon** [comment] 2018-03-22 15:23
worked for me too, I close.

**Closed** 2018-03-23 02:09 UTC
Labels: priority_major, state_verification, type_bug
